id: 47d97c268c6b4cdf843f3101eb77278d
initial_creation_type: ebook
source_metadata:
  title: the title
  subtitle: test
  authors:
  - test
  collection: test
  publisher: test
  id: test
  cover: tmpz7k6i8ak.jpg
  credit: tmpdhvx57q4.jpg
